dependencies {

    final def exclude = {
        exclude group: "com.google.guava", module: "guava"
        exclude group: "commons-codec", module: "commons-codec"
        exclude group: "com.google.code.gson", module: "gson"
        exclude group: "com.google.j2objc", module: "j2objc-annotations"
        exclude group: "com.google.code.findbugs", module: "jsr305"
    }

    implementation("com.google.apis:google-api-services-sheets:${google_api_services_sheets_version}") {
        exclude
    }
    implementation("com.google.api-client:google-api-client:${google_api_client_version}") {
        exclude
    }
    implementation("com.google.oauth-client:google-oauth-client-jetty:${google_oauth_client_jetty_version}") {
        exclude
    }

    jarJar("com.google.apis:google-api-services-sheets:${google_api_services_sheets_version}") {
        version {
            strictly "[${google_api_services_sheets_version},)"
            prefer "${google_api_services_sheets_version}"
        }
        transitive = false
        exclude
    }
    jarJar("com.google.api-client:google-api-client:${google_api_client_version}") {
        version {
            strictly "[${google_api_client_version},)"
            prefer "${google_api_client_version}"
        }
        transitive = false
        exclude
    }
    jarJar("com.google.oauth-client:google-oauth-client-jetty:${google_oauth_client_jetty_version}") {
        version {
            strictly "[${google_oauth_client_jetty_version},)"
            prefer "${google_oauth_client_jetty_version}"
        }
        transitive = false
        exclude
    }
    jarJar("com.google.oauth-client:google-oauth-client-java6:1.32.1") {
        version {
            strictly "[1.32.1,)"
            prefer "1.32.1"
        }
        transitive = false
    }
    jarJar("com.google.oauth-client:google-oauth-client:1.32.1") {
        version {
            strictly "[1.32.1,)"
            prefer "1.32.1"
        }
        transitive = false
    }
    jarJar("com.google.http-client:google-http-client-apache-v2:1.39.2") {
        version {
            strictly "[1.39.2,)"
            prefer "1.39.2"
        }
        transitive = false
    }
    jarJar("com.google.http-client:google-http-client-gson:1.39.2") {
        version {
            strictly "[1.39.2,)"
            prefer "1.39.2"
        }
        transitive = false
    }
    jarJar("com.google.http-client:google-http-client:1.39.2") {
        version {
            strictly "[1.39.2,)"
            prefer "1.39.2"
        }
        transitive = false
    }
    jarJar("io.opencensus:opencensus-api:0.28.0") {
        version {
            strictly "[0.28.0,)"
            prefer "0.28.0"
        }
        transitive = false
    }
    jarJar("io.opencensus:opencensus-contrib-http-util:0.28.0") {
        version {
            strictly "[0.28.0,)"
            prefer "0.28.0"
        }
        transitive = false
    }
    jarJar("io.grpc:grpc-context:1.27.2") {
        version {
            strictly "[1.27.2,)"
            prefer "1.27.2"
        }
        transitive = false
    }
}
